Shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^', include('main.urls'), name='main'),
    url(r'^cart/', include('cart.urls'), name='cart'),
    url(r'^order/', include('order.urls'), name='order'),
    url(r'^lk/', include('lk.urls'), name='lk')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'
urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name="CartRemove"),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail')
]

lk/urls.py
from django.conf.urls import url
from . import views

app_name = 'lk'
urlpatterns = [
    url(r'^$', views.lk, name='main'),
    url(r'orders/', views.orders, name='orders')
]

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'
urlpatterns = [
    url(r'index', views.index, name="index"),
    url(r'products', views.products, name="products"),
    url(r'registration', views.registration, name="registration"),
    url(r'logout', views.logout, name="logout"),
    url(r'auth', views.auth, name="auth"),
    url(r'omag', views.about, name="about"),
    url(r'cont', views.contacts, name="contacts"),


]

order/urls.py
from django.conf.urls import url
from . import views


app_name = 'order'
urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate')
]

cart/models.py
from django.db import models

# Create your models here.

lk/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(max_length=50)
    country = models.ForeignKey(Country, models.CASCADE, blank=True, null=True)
    def __str__(self):
        return self.name
class Product(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=200)
    image_source = models.CharField(max_length=200)
    price = models.IntegerField(null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)
    def __str__(self):
        return self.name

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

main/forms.py
from django import forms


class LoginForm(forms.Form):
    email = forms.EmailField(label='Почта', max_length=100)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())

class RegistrationForm(forms.Form):
    name = forms.CharField(label='Имя', max_length=100)
    surname = forms.CharField(label='Фамилия', max_length=100)
    email = forms.EmailField(label='Почта', max_length=100)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())

cart/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from cart.cart import Cart
from main.models import Product
from django.shortcuts import render,get_object_or_404, redirect
from cart.forms import CartAddProductForm

# Create your views here.

@csrf_exempt
@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('main:products')

def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    for item in cart.cart.items():
        print(item)
    cart.remove(product)
    return redirect('cart:CartDetail')

def CartDetail(request):
    cart = Cart(request)
    for item in cart.cart.items():
        print(item)
    return render(request, 'main/cart.html', {'cart' : cart})

lk/views.py
from django.shortcuts import render
from order.models import Order
from django.shortcuts import redirect
# Create your views here.


def lk(request):
    if(request.user):
        return render(request, 'main/lk.html', )
    return redirect("main:auth")

def orders(request):
    if(request.user):
        orders = Order.objects.filter(client=request.user)
        return render(request, 'main/zak.html', {'orders':orders})
    return redirect("main:auth")

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Product
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from .forms import LoginForm, RegistrationForm
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from cart.forms import CartAddProductForm
from order.models import Order


# Create your views here.
def index(request):
    return render(request,'main/index.html',{})

def products(request):
    products_list = Product.objects.all()
    cart_product_form = CartAddProductForm()
    return render(request, 'main/tov.html', {"products_list": products_list,
                                             "cart_product_form":cart_product_form})

def about(request):
    return render(request, 'main/omag.html',{})

def contacts(request):
    return render(request, 'main/cont.html')

@csrf_exempt
def registration(request):
    if(request.method == "POST"):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            surname = form.cleaned_data['surname']
            username = form.cleaned_data['email']
            pasword = form.cleaned_data['password']
            user = User.objects.create_user(username,'',pasword)
            user.first_name = name
            user.last_name = surname
            user.save()
            auth_login(request, user)
            return HttpResponseRedirect('/index')
        else:
            return HttpResponse('failed')
    else:
        form = RegistrationForm
        return render(request, 'main/reg.html', {'form':form})

@csrf_exempt
def auth(request):
    if(request.method == 'POST'):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                print("456")
                auth_login(request, user)
                return HttpResponseRedirect('/index')
            else:
                print(123)
                return HttpResponse('invalid login')

    else:
        form = LoginForm()
    return render(request, 'main/auth.html', {'form': form})

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/index')

templates/main/auth.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="{% static 'scripts/scripts.js' %}"></script>

</head>
<body>
        <header>
                <nav class="container1">
                    <a class="logo" href="index.html">
                        <span>L</span>
                        <span>O</span>
                        <span>G</span>
                        <span>O</span>
                    </a>
                    <ul id="auth">
                            {% if user.is_authenticated%}
                                <li><a>{{ user.username }}</a></li>
                                <li><a href="{% url "lk:main" %}">Личный кабинет</a></li>
                                <li><a href="{% url "main:logout" %}">Выход</a></li>
                            {% else %}
                                <li><a href="{% url "main:auth" %}">ВХОД</a></li>
                                <li><a href="{% url "main:registration" %}">РЕГИСТРАЦИЯ</a></li>
                            {% endif %}
                                <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        </div>
                    </li>
            </ul>
                </nav>
            </header>

    <nav class="container1">
        <ul id="menu">
            <li><a href="{% url "main:index" %}">На главную</a></li>
            <li><a href="{% url 'main:products' %}">Товары</a></li>
            <li><a href="{% url "main:about" %}">О магазине</a></li>
            <li><a href="{% url "main:contacts"%}">Контакты</a></li>
            <li><a href="{% url "cart:CartDetail" %}">Корзина</a></li>
        </ul>
    </nav>

    <div class="container1">
        <div class="rasp">
            {% csrf_token %}
            <h3>Войти на сайт</h3>
            <form action="/auth" method="post" class="ui-form" id="ui-form">
                {% csrf_token %}
                {{ form }}
                <p><input  type="submit" value="Войти"></p>
            </form>
        </div>
    </div>

    <footer>
        <div class="container1">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>

templates/main/cart.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="{% static 'scripts/scripts.js' %}"></script>

</head>
<body>
        <header>
                <nav class="container1">
                    <a class="logo" href="index.html">
                        <span>L</span>
                        <span>O</span>
                        <span>G</span>
                        <span>O</span>
                    </a>
                    <ul id="auth">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="{% url "lk:main" %}">Личный кабинет</a></li>
                    <li><a href="{% url "main:logout" %}">Выход</a></li>
                {% else %}
                    <li><a href="{% url "main:auth" %}">ВХОД</a></li>
                    <li><a href="{% url "main:registration" %}">РЕГИСТРАЦИЯ</a></li>
                {% endif %}
                    <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        </div>
                    </li>
            </ul>
                </nav>
            </header>

    <nav class="container1">
        <ul id="menu">
            <li><a href="{% url "main:index" %}">На главную</a></li>
            <li><a href="{% url 'main:products' %}">Товары</a></li>
            <li><a href="{% url "main:about" %}">О магазине</a></li>
            <li><a href="{% url "main:contacts"%}">Контакты</a></li>
            <li><a href="{% url "cart:CartDetail" %}">Корзина</a></li>
        </ul>
    </nav>

    <div class="container1">
        <div class="cart">
            <div class="cart_zag"><h2>Корзина</h2></div>
            <div class="cart_osn">
                <div class="table">
                    <table  class="tb1">
                        <tr>
                            <th>Изображение</th>
                            <th>Продукт</th>
                            <th>Колличество</th>
                            <th>Цена</th>
                            <th>Полная стоимость</th>
                            <th>Убрать из корзины</th>
                        </tr>
                            {% for item in cart %}
                                {% with product=item.product %}
                                <tr>
                                    {% load staticfiles %}
                                    <td><a href=""><img src="{% static 'img' %}/{{ product.image_source }}" alt=""></a></td>
                                    <td>{{ product.name }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>{{ item.total_price }}</td>
                                    <td><a href="{% url "cart:CartRemove" product.id %}" class="del">Удалить</a></td>
                                </tr>
                                {% endwith %}
                            {% endfor %}
                    </table>
                </div>
                <div class="zakaz">
                    <div class="padding1"> <h3>Общая стоимость: {{ cart.get_total_price }}$</h3></div>
                    <a href="{% url "order:OrderCreate" %}" class="btn">Оформить заказ</a>
                </div>
            </div>
        </div>
    </div>

    <footer>
        <div class="container1">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>

templates/main/cont.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="{% static 'scripts/scripts.js' %}"></script>

</head>
<body>
        <header>
                <nav class="container1">
                    <a class="logo" href="index.html">
                        <span>L</span>
                        <span>O</span>
                        <span>G</span>
                        <span>O</span>
                    </a>
                    <ul id="auth">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="{% url "lk:main" %}">Личный кабинет</a></li>
                    <li><a href="{% url "main:logout" %}">Выход</a></li>
                {% else %}
                    <li><a href="{% url "main:auth" %}">ВХОД</a></li>
                    <li><a href="{% url "main:registration" %}">РЕГИСТРАЦИЯ</a></li>
                {% endif %}
                    <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        </div>
                    </li>
            </ul>
                </nav>
            </header>

    <nav class="container1">
        <ul id="menu">
            <li><a href="{% url "main:index" %}">На главную</a></li>
            <li><a href="{% url 'main:products' %}">Товары</a></li>
            <li><a href="{% url "main:about" %}">О магазине</a></li>
            <li><a href="{% url "main:contacts"%}">Контакты</a></li>
            <li><a href="{% url "cart:CartDetail" %}">Корзина</a></li>
        </ul>
    </nav>
    
    <div class="container1">
        <div class="cont">
            <div class="cont_zag"><h2>Контакты</h2></div>
            <div class="cont_osn">
                <div class="osn_mapiopis">
                    <div class="mapiopis_map">
                        <div class="map">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2242.823997935828!2d37.791340316047666!3d55.79629399610415!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b534ce1ccf3169%3A0xb53ca847fa9cdc20!2zNy3RjyDQn9Cw0YDQutC-0LLQsNGPINGD0LsuLCA5LzI2LCDQnNC-0YHQutCy0LAsIDEwNTI2NA!5e0!3m2!1sru!2sru!4v1551721186812" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
                        </div>   
                    </div>
                    <div class="mapiopis_opis">
                        <div class="mapiopis_opis_zag">
                            <h2>Заголовок1</h2>
                        </div>
                        <div class="mapiopis_opis_text">
                            <p>
                                Текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                                текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                            </p>
                        </div>
                    </div>
                </div>
                <div class="cont_opis">
                        <div class="cont_opis_zag">
                            <h2>Заголовок2</h2>
                        </div>
                        <div class="cont_opis_text">
                            <p>
                                Текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                                текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                                текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                                текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                            </p>
                        </div>
                    </div>
            </div>
        </div>
    </div>

    <footer>
        <div class="container1">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>

templates/main/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="{% static 'scripts/scripts.js' %}"></script>

</head>
<body>
    <header>
        <nav class="container1">
            <a class="logo" href="index.html">
                <span>L</span>
                <span>O</span>
                <span>G</span>
                <span>O</span>
            </a>
           <ul id="auth">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="{% url "lk:main" %}">Личный кабинет</a></li>
                    <li><a href="{% url "main:logout" %}">Выход</a></li>
                {% else %}
                    <li><a href="{% url "main:auth" %}">ВХОД</a></li>
                    <li><a href="{% url "main:registration" %}">РЕГИСТРАЦИЯ</a></li>
                {% endif %}
                    <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        </div>
                    </li>
            </ul>
        </nav>
    </header>

    <nav class="container1">
        <ul id="menu">
            <li><a href="{% url "main:index" %}">На главную</a></li>
            <li><a href="{% url 'main:products' %}">Товары</a></li>
            <li><a href="{% url "main:about" %}">О магазине</a></li>
            <li><a href="{% url "main:contacts"%}">Контакты</a></li>
            <li><a href="{% url "cart:CartDetail" %}">Корзина</a></li>
        </ul>
    </nav>
    
    <footer>
        <div class="container1">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>

templates/main/lk.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="{% static 'scripts/scripts.js' %}"></script>

</head>
<body>
    <header>
        <nav class="container1">
            <a class="logo" href="index.html">
                <span>L</span>
                <span>O</span>
                <span>G</span>
                <span>O</span>
            </a>
            <ul id="auth">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="{% url "lk:main" %}">Личный кабинет</a></li>
                    <li><a href="{% url "main:logout" %}">Выход</a></li>
                {% else %}
                    <li><a href="{% url "main:auth" %}">ВХОД</a></li>
                    <li><a href="{% url "main:registration" %}">РЕГИСТРАЦИЯ</a></li>
                {% endif %}
                    <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        </div>
                    </li>
            </ul>
        </nav>
    </header>

    <nav class="container1">
        <ul id="menu">
            <li><a href="{% url "main:index" %}">На главную</a></li>
            <li><a href="{% url 'main:products' %}">Товары</a></li>
            <li><a href="{% url "main:about" %}">О магазине</a></li>
            <li><a href="{% url "main:contacts"%}">Контакты</a></li>
            <li><a href="{% url "cart:CartDetail" %}">Корзина</a></li>
        </ul>
    </nav>
    
    <div class="container1">
        <div class="lk">
            <div class="lk_zag">
                <h2>{{ user.first_name }} {{ user.last_name }} Вы вошли в систему под ником {{ user.username }}</h2>
            </div>
            <div class="lk_osn">
                <div class="allline">
                <div class="line">
                <div class="menu1">
                    <span>
                        Управление заказами

                    </span>
                    <br><br><br>
                    <ul class="uprzak">
                        <li><a href="{% url 'lk:orders' %}">Заказы</a></li><br>
                        <li><a href="">Счета</a></li><br>
                        <li><a href="">Аннулированные заказы</a></li><br>
                        <li><a href="">Возвраты товаров</a></li>
                    </ul>
                </div>

                <div class="menu1">
                    <span>
                        Личные данные / Настройки

                    </span>
                    <br><br><br><br><br><br><br>
                    <ul class="uprzak">
                            <li><a href="">Личные данные</a></li><br>
                            <li><a href="">Изменить пароль</a></li>
                    </ul>
                </div>
            </div>
            <div class="line">
                <div class="menu1"><br><br>
                    <span>

                        Бонусная программа

                    </span>
                    <br><br><br>
                        <ul class="uprzak">
                            <li><a href="">Бонусный счет</a></li><br>
                            <li><a href="">Промо-акция</a></li>
                        </ul>
                </div>
                <div class="menu1">
                    <span>
                            Сервис

                    </span>
                    <br><br><br><br><br>
                                <ul class="uprzak">
                                    <li><a href="">Список пожеланий</a></li>
                                    
                                </ul>  
                            </div>                          
                    </div>
                </div>
            </div>
        </div>
    </div>



















    <footer>
        <div class="container1">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>