Shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^', include('main.urls'), name='main'),
    url(r'^cart/', include('cart.urls'), name='cart'),
    url(r'^order/', include('order.urls'), name='order'),
    url(r'^lk/', include('lk.urls'), name='lk')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'
urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name="CartRemove"),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail')
]

lk/urls.py
from django.conf.urls import url
from . import views

app_name = 'lk'
urlpatterns = [
    url(r'^$', views.lk, name='main'),
    url(r'orders/', views.orders, name='orders')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from cart.cart import Cart
from main.models import Product
from django.shortcuts import render,get_object_or_404, redirect
from cart.forms import CartAddProductForm

# Create your views here.

@csrf_exempt
@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('main:products')

def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    for item in cart.cart.items():
        print(item)
    cart.remove(product)
    return redirect('cart:CartDetail')

def CartDetail(request):
    cart = Cart(request)
    for item in cart.cart.items():
        print(item)
    return render(request, 'main/cart.html', {'cart' : cart})

templates/pages1/auth.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="{% static 'scripts/scripts.js' %}"></script>

</head>
<body>
    <header>
        <nav class="container">
            <a class="logo" href="index.html">
                <span>L</span>
                <span>O</span>
                <span>G</span>
                <span>O</span>
            </a>
            <ul id="auth">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="">Личный кабинет</a></li>
                    <li><a href="/logout">Выход</a></li>
                {% else %}
                    <li><a href="auth">ВХОД</a></li>
                    <li><a href="registration">РЕГИСТРАЦИЯ</a></li>
                {% endif %}
                    <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        </div>
                    </li>
            </ul>
        </nav>
    </header>
    <nav class="container">
        <ul id="menu">
            <li><a href="index">На главную</a></li>
            <li><a href="products">Товары</a></li>
            <li><a href="omag">О магазине</a></li>
            <li><a href="cont.html">Контакты</a></li>
            <li><a href="">Корзина</a></li>
        </ul>
    </nav>

        <!-- НУЖНО ДОДЕЛАТЬ НОРМАЛЬНО АВТОРИЗАЦИЮ!-->

    <div class="container">
        <div class="rasp">
            {% csrf_token %}
            <form action="" class="ui-form" id="auth">
                    <h3>Войти на сайт</h3>
                     <div class="form-row">
                      <input type="text" id="email" required autocomplete="off"><label for="email">Email</label>
                    </div>
                    <div class="form-row">
                      <input type="password" id="password" required autocomplete="off"><label for="password">Пароль</label>
                    </div>
                    <p><input type="submit" value="Войти"></p>
            </form>
            <form action="/auth" method="post">
                {% csrf_token %}
                {{ form }}
                <input  type="submit" value="Submit">
            </form>

        </div>
    </div>

        <!-- НУЖНО ДОДЕЛАТЬ НОРМАЛЬНО АВТОРИЗАЦИЮ!-->

    <footer>
        <div class="container">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>

templates/pages1/cart.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="{% static 'scripts/scripts.js' %}"></script>

</head>
<body>
        <header>
        <nav class="container">
            <a class="logo" href="index.html">
                <span>L</span>
                <span>O</span>
                <span>G</span>
                <span>O</span>
            </a>
            <ul id="auth">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="">Личный кабинет</a></li>
                    <li><a href="/logout">Выход</a></li>
                {% else %}
                    <li><a href="auth">ВХОД</a></li>
                    <li><a href="registration">РЕГИСТРАЦИЯ</a></li>
                {% endif %}
            <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        <div class="descr">
                            Колличество товаров в корзине: N шт.;
                            <br>
                            Стоимость: xxx $;
                        </div>
                        </div>
                    </li>
            </ul>
        </nav>
    </header>

    <nav class="container">
        <ul id="menu">
            <li><a href="index">На главную</a></li>
            <li><a href="products">Товары</a></li>
            <li><a href="omag">О магазине</a></li>
            <li><a href="cont.html">Контакты</a></li>
            <li><a href="">Корзина</a></li>
        </ul>
    </nav>

        <div class="container1">
        <div class="cart">
            <div class="cart_zag"><h2>Корзина</h2></div>
            <div class="cart_osn">
                <div class="table">
                    <table  class="tb1">
                        <tr>
                            <th>Изображение</th>
                            <th>Продукт</th>
                            <th>Колличество</th>
                            <th>Цена</th>
                            <th>Полная стоимость</th>
                            <th>Убрать из корзины</th>
                        </tr>
                        <tr>
                            <td><a href=""><img src="img/1.png" alt=""></a></td>
                            <td>Apple Iphone 7s 64 GB [Gold]</td>
                            <td>2</td>
                            <td>720$</td>
                            <td>1440$</td>
                            <td><a href="" class="del">Удалить</a></td>
                        </tr>
                        <tr>
                                <td><a href=""><img src="img/1.png" alt=""></a></td>
                                <td>Apple Iphone 7s 64 GB [Gold]</td>
                                <td>2</td>
                                <td>720$</td>
                                <td>1440$</td>
                                <td><a href="" class="del">Удалить</a></td>
                            </tr>
                            <tr>
                                    <td><a href=""><img src="img/1.png" alt=""></a></td>
                                    <td>Apple Iphone 7s 64 GB [Gold]</td>
                                    <td>2</td>
                                    <td>720$</td>
                                    <td>1440$</td>
                                    <td><a href="" class="del">Удалить</a></td>
                                </tr>
                    </table>
                </div>
                <div class="zakaz">
                    <div class="padding1"> <h3>Общая стоимость: 4320$</h3></div>
                    <a href="oform.html">Оформить заказ</a>
                </div>
            </div>
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>

templates/pages1/cont.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="{% static 'scripts/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
</head>
<body>
    <header>
        <nav class="container">
            <a class="logo" href="index.html">
                <span>L</span>
                <span>O</span>
                <span>G</span>
                <span>O</span>
            </a>
            <ul id="auth">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="">Личный кабинет</a></li>
                    <li><a href="/logout">Выход</a></li>
                {% else %}
                    <li><a href="auth">ВХОД</a></li>
                    <li><a href="registration">РЕГИСТРАЦИЯ</a></li>
                {% endif %}
                <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        <div class="descr">
                            Колличество товаров в корзине: N шт.;
                            <br>
                            Стоимость: xxx $;
                        </div>
                        </div>
                    </li>
            </ul>
        </nav>
    </header>
    <nav class="container">
        <ul id="menu">
            <li><a href="index">На главную</a></li>
            <li><a href="products">Товары</a></li>
            <li><a href="omag">О магазине</a></li>
            <li><a href="cont.html">Контакты</a></li>
            <li><a href="">Корзина</a></li>
        </ul>
    </nav>
    

































    <div class="container">
        <div class="cont">
            <div class="cont_zag"><h2>Контакты</h2></div>
            <div class="cont_osn">
                <div class="osn_mapiopis">
                    <div class="mapiopis_map">
                        <div class="map">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2242.823997935828!2d37.791340316047666!3d55.79629399610415!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b534ce1ccf3169%3A0xb53ca847fa9cdc20!2zNy3RjyDQn9Cw0YDQutC-0LLQsNGPINGD0LsuLCA5LzI2LCDQnNC-0YHQutCy0LAsIDEwNTI2NA!5e0!3m2!1sru!2sru!4v1551721186812" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
                        </div>   
                    </div>
                    <div class="mapiopis_opis">
                        <div class="mapiopis_opis_zag">
                            <h2>Заголовок1</h2>
                        </div>
                        <div class="mapiopis_opis_text">
                            <p>
                                Текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                                текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                            </p>
                        </div>
                    </div>
                </div>
                <div class="cont_opis">
                        <div class="cont_opis_zag">
                            <h2>Заголовок2</h2>
                        </div>
                        <div class="cont_opis_text">
                            <p>
                                Текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                                текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                                текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                                текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                            </p>
                        </div>
                    </div>
            </div>
        </div>
    </div>















































    



    <footer>
        <div class="container">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>

templates/pages1/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <script src="{% static 'scripts/scripts.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
</head>
<body>
    <header>
        <nav class="container">
            <a class="logo" href="index.html">
                <span>L</span>
                <span>O</span>
                <span>G</span>
                <span>O</span>
            </a>
            <ul id="auth">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="">Личный кабинет</a></li>
                    <li><a href="/logout">Выход</a></li>
                {% else %}
                    <li><a href="auth">ВХОД</a></li>
                    <li><a href="registration">РЕГИСТРАЦИЯ</a></li>
                {% endif %}
            <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        <div class="descr">
                            Колличество товаров в корзине: N шт.;
                            <br>
                            Стоимость: xxx $;
                        </div>
                        </div>
                    </li>
            </ul>
        </nav>
    </header>



    <nav class="container">
        <ul id="menu">
            <li><a href="index">На главную</a></li>
            <li><a href="products">Товары</a></li>
            <li><a href="omag">О магазине</a></li>
            <li><a href="cont.html">Контакты</a></li>
            <li><a href="">Корзина</a></li>
        </ul>
    </nav>






    <footer>
        <div class="container">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>

templates/pages1/omag.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <script src="{% static 'scripts/scripts.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
</head>
<body>
    <header>
        <nav class="container">
            <a class="logo" href="index.html">
                <span>L</span>
                <span>O</span>
                <span>G</span>
                <span>O</span>
            </a>
            <ul id="auth">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="">Личный кабинет</a></li>
                    <li><a href="/logout">Выход</a></li>
                {% else %}
                    <li><a href="auth">ВХОД</a></li>
                    <li><a href="registration">РЕГИСТРАЦИЯ</a></li>
                {% endif %}
            <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        </div>
                    </li>
            </ul>
        </nav>
    </header>
    <nav class="container">
        <ul id="menu">
            <li><a href="index">На главную</a></li>
            <li><a href="products">Товары</a></li>
            <li><a href="">О магазине</a></li>
            <li><a href="cont.html">Контакты</a></li>
            <li><a href="">Корзина</a></li>
        </ul>
    </nav>
    




    <div class="container">
        <div class="omag">
            <div class="omag_zag"><h2>О магазине</h2></div>
            <div class="omag_osn">
                <div class="omag_osn_img"><img src="img/1.png" alt=""></div>
                <div class="omag_osn_opis">
                    <div class="omag_osn_opis_zag"><h2>Заголовок</h2></div>
                    <div class="omag_osn_opis_text">
                        <p>
                            Текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст 
                            текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                            текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст текст
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>









    <footer>
        <div class="container">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>

templates/pages1/tov.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
    {% load staticfiles %}
    <script src="{% static 'scripts/scripts.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
</head>
<body>
    <header>
        <nav class="container">
            <a class="logo" href="index.html">
                <span>L</span>
                <span>O</span>
                <span>G</span>
                <span>O</span>
            </a>
            <ul id="auth">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="">Личный кабинет</a></li>
                    <li><a href="/logout">Выход</a></li>
                {% else %}
                    <li><a href="auth">ВХОД</a></li>
                    <li><a href="registration">РЕГИСТРАЦИЯ</a></li>
                {% endif %}
            <li>
                        <div class="poster">
                            <a href="{% url 'cart:CartDetail' %}" class="noanim"><img src="{% static 'img/cart.png' %}" style="display: inline-block !important;"></a>
                        <div class="descr">
                            Колличество товаров в корзине: {{ cart.get_number_of_items}} шт.;
                            <br>
                            Стоимость: {{ cart.get_total_price }} $;
                        </div>
                        </div>
                    </li>
            </ul>
        </nav>
    </header>
    <nav class="container">
        <ul id="menu">
            <li><a href="index">На главную</a></li>
            <li><a href="products">Товары</a></li>
            <li><a href="omag">О магазине</a></li>
            <li><a href="cont.html">Контакты</a></li>
            <li><a href="">Корзина</a></li>
        </ul>
    </nav>
    
    
    <!-- НУЖНО ДОДЕЛАТЬ НОРМАЛЬНО ТОВАРЫ!-->


    <div class="container">
        <div class="glav">
            <div class="glav_zag"><h2>Заголовок</h2></div>
            <div class="allline">
                <div class="line">
                    {% if products_list %}
                        {% for product in products_list %}
                            <div class="tovar">
                                {% load staticfiles %}
                                <div class="tovar_img"><img src="{% static 'img'%}/{{ product.image_source }}" alt=""></div>
                                <div class="opis">
                                    <div class="opis_zag"><h2>{{ product}}</h2></div>
                                    <div class="opis_text">
                                        <p>{{ product.description }}</p>
                                        <p>{{ product.company}}</p>
                                        <p>{{ product.company.country }}</p>
                                        <form action="{% url "cart:CartAdd" product.id %}" method="post">
                                            {{ cart_product_form }}
                                            {% csrf_token %}
                                            <input type="submit" value="Добавить в корзину">
                                        </form>
                                    </div>
                                </div>
                                <div class="pert"><a href="">Подробнее</a></div>

                    </div>
                    {% endfor %}
                    {% endif %}

                    </div>
            </div>



            <!-- НОМЕР СТРАНИЦЫ !-->
            <div class="container">
                    <div class="item-list">
                        <ul class="pager">
                        <li class="pager-current first"><span>1</span></li>
                        <li class="pager-item"><a href="/node?page=1" title="На страницу номер 2">2</a></li>
                        <li class="pager-item"><a href="/node?page=2" title="На страницу номер 3">3</a></li>
                        <li class="pager-item"><a href="/node?page=3" title="На страницу номер 4">4</a></li>
                        <li class="pager-next last"><a href="/node?page=1" title="На следующую страницу">›</a></li>
                        </ul>
                    </div>
            </div>
            <!-- НОМЕР СТРАНИЦЫ !-->    


        </div>
    </div>


    <!-- НУЖНО ДОДЕЛАТЬ НОРМАЛЬНО ТОВАРЫ!-->





    <footer>
        <div class="container">
            <div class="footer-col"><span>Интернет магазин © 2019</span></div>
            <div class="footer-col">
                <div class="social-bar-wrap">
                    <a title="Вконтакте" href="https://vk.com/dmitryluchinkin" target="_blank"><i class="fa fa-vk"></i></a>
                    <a title="Instagram" href="https://www.instagram.com/luchinkindmitry/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a>
                </div>
            </div>
            <div class="footer-col">
                <a href="mailto:luchinkindmitry@gmail.com">E-mail</a>
            </div>
        </div>
    </footer>
</body>
</html>